project_id = "bkrjpqdsnmysxloadmev"

[functions.invite-volunteer]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.register-visitor]
verify_jwt = false

[functions.send-birthday-emails]
verify_jwt = false

[functions.send-password-reset]
verify_jwt = false

[functions.twilio-inbound-sms]
verify_jwt = false
