#!/usr/bin/env node
/**
 * HOTC Print Bridge
 * ------------------------------------------------------------------
 * Tiny LAN server that accepts raster print jobs from the web app
 * and forwards them to a Brother QL-1110NWB (or QL-800 series)
 * connected via USB or on the same network (port 9100 raw TCP).
 *
 * Endpoints:
 *   GET  /            -> health check + small test page
 *   GET  /status      -> JSON status (printer reachable?)
 *   POST /print       -> body: { rasterBase64: string }  prints raw bytes
 *
 * Config via environment variables (or .env):
 *   PRINTER_HOST   e.g. 192.168.1.60   (network printer mode)
 *   PRINTER_PORT   default 9100
 *   USB_DEVICE     e.g. /dev/usb/lp0   (Linux USB mode)
 *   WIN_PRINTER    e.g. "Brother QL-1110NWB"  (Windows: piped to print spooler)
 *   HTTP_PORT      default 9999
 *   HTTPS_PORT     default 9443
 *   CERT_DIR       default ./cert   (cert.pem + key.pem)
 *
 * The web app (HTTPS) cannot POST to an HTTP LAN URL (mixed-content),
 * so prefer HTTPS with the self-signed cert generated by generate-cert.sh.
 * On iPad: install cert.pem once via AirDrop -> Settings -> Profile.
 */
const http = require("http");
const https = require("https");
const net = require("net");
const fs = require("fs");
const path = require("path");
const os = require("os");
const { spawn } = require("child_process");

// Optional: bonjour-service for mDNS/Bonjour advertisement (auto-discovery
// from kiosks on the same wifi). If the dep isn't installed, the bridge
// still works — kiosks just have to enter the IP manually.
let Bonjour = null;
try { Bonjour = require("bonjour-service").Bonjour; } catch { /* optional */ }

const PRINTER_HOST = process.env.PRINTER_HOST || "";
const PRINTER_PORT = parseInt(process.env.PRINTER_PORT || "9100", 10);
const USB_DEVICE = process.env.USB_DEVICE || "";
const WIN_PRINTER = process.env.WIN_PRINTER || "";
const HTTP_PORT = parseInt(process.env.HTTP_PORT || "9999", 10);
const HTTPS_PORT = parseInt(process.env.HTTPS_PORT || "9443", 10);
const CERT_DIR = process.env.CERT_DIR || path.join(__dirname, "cert");

function log(...args) {
  console.log(new Date().toISOString(), ...args);
}

function sendBytesToPrinter(bytes) {
  return new Promise((resolve, reject) => {
    if (PRINTER_HOST) {
      const sock = new net.Socket();
      sock.setTimeout(10000);
      sock.connect(PRINTER_PORT, PRINTER_HOST, () => {
        sock.write(Buffer.from(bytes), () => sock.end());
      });
      sock.on("close", () => resolve({ via: `tcp://${PRINTER_HOST}:${PRINTER_PORT}` }));
      sock.on("timeout", () => { sock.destroy(); reject(new Error("Printer TCP timeout")); });
      sock.on("error", reject);
      return;
    }
    if (USB_DEVICE) {
      try {
        fs.writeFileSync(USB_DEVICE, Buffer.from(bytes));
        return resolve({ via: USB_DEVICE });
      } catch (e) {
        return reject(e);
      }
    }
    if (WIN_PRINTER) {
      // Windows: pipe bytes to default print via lpr / print command
      const child = spawn("powershell.exe", [
        "-Command",
        `$bytes=[Console]::In.ReadToEnd();[System.IO.File]::WriteAllBytes("$env:TEMP\\hotc_label.prn",[System.Text.Encoding]::GetEncoding(28591).GetBytes($bytes));Start-Process -FilePath "print" -ArgumentList "/D:\\\\localhost\\${WIN_PRINTER.replace(/"/g, '')} $env:TEMP\\hotc_label.prn" -Wait -NoNewWindow`,
      ]);
      child.stdin.end(Buffer.from(bytes));
      child.on("close", (code) => code === 0 ? resolve({ via: WIN_PRINTER }) : reject(new Error("Windows print failed, code " + code)));
      child.on("error", reject);
      return;
    }
    reject(new Error("No printer transport configured. Set PRINTER_HOST, USB_DEVICE, or WIN_PRINTER."));
  });
}

async function probePrinter() {
  if (PRINTER_HOST) {
    return new Promise((resolve) => {
      const sock = new net.Socket();
      sock.setTimeout(2000);
      sock.connect(PRINTER_PORT, PRINTER_HOST, () => { sock.destroy(); resolve(true); });
      sock.on("timeout", () => { sock.destroy(); resolve(false); });
      sock.on("error", () => resolve(false));
    });
  }
  if (USB_DEVICE) return fs.existsSync(USB_DEVICE);
  if (WIN_PRINTER) return true; // assume installed
  return false;
}

const CORS_HEADERS = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Methods": "GET, POST, OPTIONS",
  "Access-Control-Allow-Headers": "Content-Type",
  "Access-Control-Max-Age": "86400",
};

async function handler(req, res) {
  Object.entries(CORS_HEADERS).forEach(([k, v]) => res.setHeader(k, v));

  if (req.method === "OPTIONS") { res.writeHead(204); return res.end(); }

  if (req.method === "GET" && req.url === "/") {
    res.writeHead(200, { "Content-Type": "text/html" });
    return res.end(`<!doctype html><meta charset=utf-8><title>HOTC Print Bridge</title>
<body style="font-family:system-ui;max-width:520px;margin:40px auto;padding:0 16px">
<h1>HOTC Print Bridge</h1>
<p>Bridge is running. <a href="/status">/status</a></p>
<p>Configure your kiosk to use this URL as the printer.</p>
</body>`);
  }

  if (req.method === "GET" && req.url === "/status") {
    const reachable = await probePrinter();
    res.writeHead(200, { "Content-Type": "application/json" });
    return res.end(JSON.stringify({
      ok: true,
      transport: PRINTER_HOST ? "network" : USB_DEVICE ? "usb-linux" : WIN_PRINTER ? "windows" : "none",
      target: PRINTER_HOST || USB_DEVICE || WIN_PRINTER || null,
      reachable,
      version: "1.0.0",
    }));
  }

  if (req.method === "POST" && req.url === "/print") {
    let body = "";
    req.on("data", (c) => { body += c; if (body.length > 5_000_000) { req.destroy(); } });
    req.on("end", async () => {
      try {
        const parsed = JSON.parse(body);
        if (!parsed.rasterBase64) throw new Error("Missing rasterBase64");
        const bytes = Buffer.from(parsed.rasterBase64, "base64");
        const result = await sendBytesToPrinter(bytes);
        log("printed", bytes.length, "bytes", result);
        res.writeHead(200, { "Content-Type": "application/json" });
        res.end(JSON.stringify({ ok: true, bytes: bytes.length, ...result }));
      } catch (e) {
        log("print error", e.message);
        res.writeHead(500, { "Content-Type": "application/json" });
        res.end(JSON.stringify({ ok: false, error: e.message }));
      }
    });
    return;
  }

  res.writeHead(404, { "Content-Type": "application/json" });
  res.end(JSON.stringify({ ok: false, error: "Not found" }));
}

http.createServer(handler).listen(HTTP_PORT, "0.0.0.0", () => {
  log(`HTTP  listening on 0.0.0.0:${HTTP_PORT}`);
});

const certPath = path.join(CERT_DIR, "cert.pem");
const keyPath = path.join(CERT_DIR, "key.pem");
if (fs.existsSync(certPath) && fs.existsSync(keyPath)) {
  https.createServer({
    cert: fs.readFileSync(certPath),
    key: fs.readFileSync(keyPath),
  }, handler).listen(HTTPS_PORT, "0.0.0.0", () => {
    log(`HTTPS listening on 0.0.0.0:${HTTPS_PORT}`);
  });
} else {
  log(`No certs at ${CERT_DIR} — run ./generate-cert.sh for HTTPS (required for mobile browsers loading the app from teams.hotc.life)`);
}

// ---------- mDNS / Bonjour advertisement ----------
// Advertises the bridge as `_hotc-print._tcp` on the LAN and also as a
// plain `_http` service, so kiosks can discover it automatically.
// Also publishes the hostname `hotc-print-bridge.local` — every modern OS
// (iOS, macOS, Windows 10+, most Android) resolves `.local` via mDNS,
// which lets the web app connect to a stable URL with no IP typing.
if (Bonjour) {
  try {
    const bonjour = new Bonjour();
    const hostname = "hotc-print-bridge";
    const txt = {
      transport: PRINTER_HOST ? "network" : USB_DEVICE ? "usb" : WIN_PRINTER ? "windows" : "none",
      https: String(HTTPS_PORT),
      http: String(HTTP_PORT),
      version: "1.1.0",
    };
    bonjour.publish({ name: "HOTC Print Bridge", type: "hotc-print", protocol: "tcp", port: HTTPS_PORT, host: `${hostname}.local`, txt });
    bonjour.publish({ name: "HOTC Print Bridge", type: "https",      protocol: "tcp", port: HTTPS_PORT, host: `${hostname}.local`, txt });
    log(`mDNS advertised as https://${hostname}.local:${HTTPS_PORT} (service _hotc-print._tcp)`);
    const shutdown = () => { try { bonjour.unpublishAll(() => bonjour.destroy()); } catch {} process.exit(0); };
    process.on("SIGINT", shutdown);
    process.on("SIGTERM", shutdown);
  } catch (e) {
    log("mDNS advertisement failed:", e.message);
  }
} else {
  log("bonjour-service not installed — skipping mDNS advertisement. Run `npm install` in print-bridge/ to enable auto-discovery.");
}

// Log the LAN IPs so the operator can paste one into the kiosk if mDNS
// isn't available on their network.
const ips = Object.values(os.networkInterfaces()).flat()
  .filter((i) => i && i.family === "IPv4" && !i.internal)
  .map((i) => i.address);
log("LAN URLs:", ips.map((ip) => `https://${ip}:${HTTPS_PORT}`).join("  "));
log("Config:", { PRINTER_HOST, PRINTER_PORT, USB_DEVICE, WIN_PRINTER });

